using System;
using System.Collections.Generic;

using cwkGestao.Modelo;
using cwkGestao.Modelo.Cte;
using cwkGestao.Modelo.Proxy;
using cwkGestao.Repositorio.cwkGestaoNHibernate.Helpers;
using cwkGestao.Repositorio.cwkGestaoNHibernate.Repositorios;

namespace cwkGestao.Repositorio.cwkGestaoNHibernate
{
    internal static class RepositoriosNHibernate
    {
        internal static Dictionary<Type, object> Repositorios { get; set; }

        static RepositoriosNHibernate()
        {

            Repositorios = new Dictionary<Type, object>();
            Repositorios.Add(typeof(AcompanhamentoOS), new AcompanhamentoOSRepositorio());
            Repositorios.Add(typeof(Acrescimo), new AcrescimoRepositorio());
            Repositorios.Add(typeof(Baixa), new BaixaRepositorio());
            Repositorios.Add(typeof(BaixaDocumento), new BaixaDocumentoRepositorio());
            Repositorios.Add(typeof(Balanco), new BalancoRepositorio());
            Repositorios.Add(typeof(BalancoItem), new BalancoItemRepositorio());
            Repositorios.Add(typeof(Banco), new BancoRepositorio());
            Repositorios.Add(typeof(CentroCusto), new CentroCustoRepositorio());
            Repositorios.Add(typeof(Cidade), new CidadeRepositorio());
            Repositorios.Add(typeof(Classificacao), new ClassificacaoRepositorio());
            Repositorios.Add(typeof(ClassificacaoOrdemProducao), new ClassificacaoOrdemProducaoRepositorio());
            Repositorios.Add(typeof(ClienteRevenda), new ClienteRevendaRepositorio());
            Repositorios.Add(typeof(Condicao), new CondicaoRepositorio());
            Repositorios.Add(typeof(CondicaoParcela), new CondicaoParcelaRepositorio());
            Repositorios.Add(typeof(Configuracao), new ConfiguracaoRepositorio());
            Repositorios.Add(typeof(ControleQualidade), new ControleQualidadeRepositorio());
            Repositorios.Add(typeof(Cor), new CorRepositorio());
            Repositorios.Add(typeof(Cotacao), new CotacaoRepositorio());
            Repositorios.Add(typeof(CotacaoProduto), new CotacaoProdutoRepositorio());
            Repositorios.Add(typeof(CotacaoProdutoPedidoItem), new CotacaoProdutoPedidoItemRepositorio());
            Repositorios.Add(typeof(CQEquipamento), new CQEquipamentoRepositorio());
            Repositorios.Add(typeof(CQFuncionario), new CQFuncionarioRepositorio());
            Repositorios.Add(typeof(CQProduto), new CQProdutoRepositorio());
            Repositorios.Add(typeof(CwkPedido), new CwkPedidoRepositorio());
            Repositorios.Add(typeof(CwkPedidoEmpresa), new CwkPedidoEmpresaRepositorio());
            Repositorios.Add(typeof(Cw_acesso), new Cw_acessoRepositorio());
            Repositorios.Add(typeof(Cw_acessocampo), new Cw_acessocampoRepositorio());
            Repositorios.Add(typeof(Cw_grupo), new Cw_grupoRepositorio());
            Repositorios.Add(typeof(Cw_usuario), new Cw_usuarioRepositorio());
            Repositorios.Add(typeof(Documento), new DocumentoRepositorio());
            Repositorios.Add(typeof(Empresa), new EmpresaRepositorio());
            Repositorios.Add(typeof(OSEquipamento), new OSEquipamentoRepositorio());
            Repositorios.Add(typeof(Estoque), new EstoqueRepositorio());
            Repositorios.Add(typeof(EtapaProducao), new EtapaProducaoRepositorio());
            Repositorios.Add(typeof(Ficha), new FichaRepositorio());
            Repositorios.Add(typeof(FichaTecnica), new FichaTecnicaRepositorio());
            Repositorios.Add(typeof(Ficha_Produto), new Ficha_ProdutoRepositorio());
            Repositorios.Add(typeof(Filial), new FilialRepositorio());
            Repositorios.Add(typeof(GrupoEstoque), new GrupoEstoqueRepositorio());
            Repositorios.Add(typeof(Grupo1), new Grupo1Repositorio());
            Repositorios.Add(typeof(Grupo2), new Grupo2Repositorio());
            Repositorios.Add(typeof(Grupo3), new Grupo3Repositorio());
            Repositorios.Add(typeof(HistMovimentoRemessaDoc), new HistMovimentoRemessaDocRepositorio());
            Repositorios.Add(typeof(Historico), new HistoricoRepositorio());
            Repositorios.Add(typeof(ICMS), new ICMSRepositorio());
            Repositorios.Add(typeof(ICMS_Interestadual), new ICMS_InterestadualRepositorio());
            Repositorios.Add(typeof(Impressora), new ImpressoraRepositorio());
            Repositorios.Add(typeof(ItemFichaTecnica), new ItemFichaTecnicaRepositorio());
            Repositorios.Add(typeof(MovCaixa), new MovCaixaRepositorio());
            Repositorios.Add(typeof(Movimento), new MovimentoRepositorio());
            Repositorios.Add(typeof(NFe_Erro), new NFe_ErroRepositorio());
            Repositorios.Add(typeof(Nota), new NotaRepositorio());
            Repositorios.Add(typeof(NotaICMS), new NotaICMSRepositorio());
            Repositorios.Add(typeof(NotaItem), new NotaItemRepositorio());
            Repositorios.Add(typeof(NotaParcela), new NotaParcelaRepositorio());
            Repositorios.Add(typeof(Operacao), new OperacaoRepositorio());
            Repositorios.Add(typeof(OrdemProducao), new OrdemProducaoRepositorio());
            Repositorios.Add(typeof(OrdemProducaoExecucao), new OrdemProducaoExecucaoRepositorio());
            Repositorios.Add(typeof(OrdemProducaoExecucaoProduto), new OrdemProducaoExecucaoProdutoRepositorio());
            Repositorios.Add(typeof(OrdemProducaoHistorico), new OrdemProducaoHistoricoRepositorio());
            Repositorios.Add(typeof(OrdemServico), new OrdemServicoRepositorio());
            Repositorios.Add(typeof(Pais), new PaisRepositorio());
            Repositorios.Add(typeof(Pedido), new PedidoRepositorio());
            Repositorios.Add(typeof(PedidoItem), new PedidoItemRepositorio());
            Repositorios.Add(typeof(PedidoParcela), new PedidoParcelaRepositorio());
            Repositorios.Add(typeof(Pessoa), new PessoaRepositorio());
            Repositorios.Add(typeof(PessoaAviso), new PessoaAvisoRepositorio());
            Repositorios.Add(typeof(PessoaCliente), new PessoaClienteRepositorio());
            Repositorios.Add(typeof(PessoaEmail), new PessoaEmailRepositorio());
            Repositorios.Add(typeof(PessoaEndereco), new PessoaEnderecoRepositorio());
            Repositorios.Add(typeof(PessoaFuncionario), new PessoaFuncionarioRepositorio());
            Repositorios.Add(typeof(PessoaSocio), new PessoaSocioRepositorio());
            Repositorios.Add(typeof(PessoaTelefone), new PessoaTelefoneRepositorio());
            Repositorios.Add(typeof(PessoaVendedor), new PessoaVendedorRepositorio());
            Repositorios.Add(typeof(PlanoConta), new PlanoContaRepositorio());
            Repositorios.Add(typeof(PlanoNegocio), new PlanoNegocioRepositorio());
            Repositorios.Add(typeof(PlanoNegocioOperacao), new PlanoNegocioOperacaoRepositorio());
            Repositorios.Add(typeof(Portador), new PortadorRepositorio());
            Repositorios.Add(typeof(Produto), new ProdutoRepositorio());
            Repositorios.Add(typeof(ProdutoVendedorComissao), new ProdutoVendedorComissaoRepositorio());
            Repositorios.Add(typeof(Produto_Icms), new Produto_IcmsRepositorio());
            Repositorios.Add(typeof(Projeto), new ProjetoRepositorio());
            Repositorios.Add(typeof(ProjetoHistorico), new ProjetoHistoricoRepositorio());
            Repositorios.Add(typeof(Projeto_Material), new Projeto_MaterialRepositorio());
            Repositorios.Add(typeof(Projeto_ProdutoServico), new Projeto_ProdutoServicoRepositorio());
            Repositorios.Add(typeof(Rateio_Mov), new Rateio_MovRepositorio());
            Repositorios.Add(typeof(Rateio_NotaItem), new Rateio_NotaItemRepositorio());
            Repositorios.Add(typeof(Remessa), new RemessaRepositorio());
            Repositorios.Add(typeof(Reparcelamento), new ReparcelamentoRepositorio());
            Repositorios.Add(typeof(ReparcelamentoDoc), new ReparcelamentoDocRepositorio());
            Repositorios.Add(typeof(Servico), new ServicoRepositorio());
            Repositorios.Add(typeof(ServicoOS), new ServicoOSRepositorio());
            Repositorios.Add(typeof(Sistema), new SistemaRepositorio());
            Repositorios.Add(typeof(Socio), new SocioRepositorio());
            Repositorios.Add(typeof(StatusOrdemServico), new StatusOrdemServicoRepositorio());
            Repositorios.Add(typeof(TabelaCFOP), new TabelaCFOPRepositorio());
            Repositorios.Add(typeof(TabelaComissao), new TabelaComissaoRepositorio());
            Repositorios.Add(typeof(TabelaComissaoProduto), new TabelaComissaoProdutoRepositorio());
            Repositorios.Add(typeof(TabelaFaixaFatSimples), new TabelaFaixaFatSimplesRepositorio());
            Repositorios.Add(typeof(TabelaICMS), new TabelaICMSRepositorio());
            Repositorios.Add(typeof(TabelaPreco), new TabelaPrecoRepositorio());
            Repositorios.Add(typeof(TabelaPrecoProduto), new TabelaPrecoProdutoRepositorio());
            Repositorios.Add(typeof(TipoAtendimento), new TipoAtendimentoRepositorio());
            Repositorios.Add(typeof(TipoDocumento), new TipoDocumentoRepositorio());
            Repositorios.Add(typeof(OSTipoEquipamento), new OSTipoEquipamentoRepositorio());
            Repositorios.Add(typeof(TipoNota), new TipoNotaRepositorio());
            Repositorios.Add(typeof(TipoPedido), new TipoPedidoRepositorio());
            Repositorios.Add(typeof(UF), new UFRepositorio());
            Repositorios.Add(typeof(Unidade), new UnidadeRepositorio());
            Repositorios.Add(typeof(Versao), new VersaoRepositorio());
            Repositorios.Add(typeof(VersaoBD), new VersaoBDRepositorio());
            Repositorios.Add(typeof(Feriado), new FeriadoRepositorio());
            Repositorios.Add(typeof(NotaServico), new NotaServicoRepositorio());
            Repositorios.Add(typeof(NotaServicoItem), new NotaServicoItemRepositorio());
            Repositorios.Add(typeof(FormaPagamento), new FormaPagamentoRepositorio());
            Repositorios.Add(typeof(FormaPgtoMovimento), new FormaPgtoMovimentoRepositorio());
            Repositorios.Add(typeof(PedidoHistorico), new PedidoHistoricoRepositorio());
            Repositorios.Add(typeof(OSOrdemServico), new OSOrdemServicoRepositorio());
            Repositorios.Add(typeof(OSAgendamento), new OSAgendamentoRepositorio());
            Repositorios.Add(typeof(ServicoImposto), new ServicoImpostoRepositorio());
            Repositorios.Add(typeof(ProjetoParcela), new ProjetoParcelaRepositorio());
            Repositorios.Add(typeof(NCM), new NCMRepositorio());
            Repositorios.Add(typeof(CEST), new CESTRepositorio());
            Repositorios.Add(typeof(CEST_Segmento), new RepositorioCEST_Segmento());
            Repositorios.Add(typeof(NCMItem), new NCMItemRepositorio());
            Repositorios.Add(typeof(RegistrosTipo60), new RegistrosTipo60Repositorio());
            Repositorios.Add(typeof(Cheque), new ChequeRepositorio());
            Repositorios.Add(typeof(MovimentacaoCheque), new MovimentacaoChequeRepositorio());
            Repositorios.Add(typeof(ChequeHistorico), new ChequeHistoricoRepositorio());
            Repositorios.Add(typeof(NotaItemServico), new NotaItemServicoRepositorio());
            Repositorios.Add(typeof(FrenteCaixaNota), new FrenteCaixaNotaRepositorio());
            Repositorios.Add(typeof(FrenteCaixaNotaItem), new FrenteCaixaNotaItemRepositorio());
            Repositorios.Add(typeof(MagentoConfiguracao), new MagentoConfiguracaoRepositorio());
            Repositorios.Add(typeof(AdicaoNotaItem), new AdicaoNotaItemRepositorio());
            Repositorios.Add(typeof(Tel_Ligacao), new Tel_LigacaoRepositorio());
            Repositorios.Add(typeof(Tel_ArquivoLigacao), new Tel_ArquivoLigacaoRepositorio());
            Repositorios.Add(typeof(Tel_GrupoCliente), new Tel_GrupoClienteRepositorio());
            Repositorios.Add(typeof(Tel_GrupoClientePreco), new Tel_GrupoClientePrecoRepositorio());
            Repositorios.Add(typeof(Tel_TipoLigacao), new Tel_TipoLigacaoRepositorio());
            Repositorios.Add(typeof(Tel_GrupoClienteTelefone), new Tel_GrupoClienteTelefoneRepositorio());
            Repositorios.Add(typeof(Tel_Cliente), new Tel_ClienteRepositorio());
            Repositorios.Add(typeof(Tel_Servico), new Tel_ServicoRepositorio());
            Repositorios.Add(typeof(Tel_FaturaD8), new Tel_FaturaD8Repositorio());
            Repositorios.Add(typeof(Tel_ClientePreco), new Tel_ClientePrecoRepositorio());
            Repositorios.Add(typeof(Tel_ClienteServico), new Tel_ClienteServicoRepositorio());
            Repositorios.Add(typeof(Tel_ClienteTelefone), new Tel_ClienteTelefoneRepositorio());
            Repositorios.Add(typeof(Tel_Fatura), new Tel_FaturaRepositorio());
            Repositorios.Add(typeof(Tel_FaturaLigacao), new Tel_FaturaLigacaoRepositorio());
            Repositorios.Add(typeof(Tel_FaturaServico), new Tel_FaturaServicoRepositorio());
            Repositorios.Add(typeof(Tel_TipoLigacaoPreco), new Tel_TipoLigacaoPrecoRepositorio());
            Repositorios.Add(typeof(Tel_Configuracao), new Tel_ConfiguracaoRepositorio());
            Repositorios.Add(typeof(PessoaEngenheiro), new PessoaEngenheiroRepositorio());
            Repositorios.Add(typeof(Ofd_Maquinas), new Ofd_MaquinasRepositorio());
            Repositorios.Add(typeof(Ofd_Obra), new Ofd_ObraRepositorio());
            Repositorios.Add(typeof(Ofd_ObraDiario), new Ofd_ObraDiarioRepositorio());
            Repositorios.Add(typeof(Ofd_ObraArquivos), new Ofd_ObraArquivosRepositorio());
            Repositorios.Add(typeof(Ofd_Proposta), new Ofd_PropostaRepositorio());
            Repositorios.Add(typeof(Ofd_PropostaArquivos), new Ofd_PropostaArquivosRepositorio());
            Repositorios.Add(typeof(Ofd_PropostaPerfuracoes), new Ofd_PropostaPerfuracoesRepositorio());
            Repositorios.Add(typeof(Ofd_PropostaMedicao), new Ofd_PropostaMedicaoRepositorio());
            Repositorios.Add(typeof(Ofd_PropostaMedicaoPerfuracao), new Ofd_PropostaMedicaoPerfuracaoRepositorio());
            Repositorios.Add(typeof(Contrato), new ContratoRepositorio());
            Repositorios.Add(typeof(ContratoServico), new ContratoServicoRepositorio());
            Repositorios.Add(typeof(NotaImpostoServico), new NotaImpostoServicoRepositorio());
            Repositorios.Add(typeof(CartaCorrecao), new CartaCorrecaoRepositorio());
            Repositorios.Add(typeof(Inventario), new InventarioRepositorio());
            Repositorios.Add(typeof(InventarioProduto), new InventarioProdutoRepositorio());
            Repositorios.Add(typeof(Ofd_Medicao), new Ofd_MedicaoRepositorio());
            Repositorios.Add(typeof(Ofd_MedicaoServicos), new Ofd_MedicaoServicosRepositorio());
            Repositorios.Add(typeof(NotaItemEstoque), new NotaItemEstoqueRepositorio());
            Repositorios.Add(typeof(Identificador), new IdentificadorRepositorio());
            Repositorios.Add(typeof(EstoqueIdentificador), new EstoqueIdentificadorRepositorio());
            Repositorios.Add(typeof(LocalEstoque), new LocalEstoqueRepositorio());
            Repositorios.Add(typeof(SincronismoPendente), new SincronismoPendenteRepositorio());
            Repositorios.Add(typeof(PedidoItemEstoque), new PedidoItemEstoqueRepositorio());
            Repositorios.Add(typeof(TextoLei), new TextoLeiRepositorio());
            Repositorios.Add(typeof(ProdutoCodBarra), new ProdutoCodBarraRepositorio());
            Repositorios.Add(typeof(TipoServicoTransporte), new TipoServicoTransporteRepositorio());
            Repositorios.Add(typeof(RastreamentoCorreio), new RastreamentoCorreioRepositorio());
            Repositorios.Add(typeof(ExpedicaoItem), new ExpedicaoItemRepositorio());
            Repositorios.Add(typeof(ProdutoSKU), new ProdutoSKURepositorio());
            Repositorios.Add(typeof(NotaItemPedidoItem), new NotaItemPedidoItemRepositorio());
            Repositorios.Add(typeof(ExpedicaoRastreamento), new ExpedicaoRastreamentoRepositorio());
            Repositorios.Add(typeof(StatusEntrega), new StatusEntregaRepositorio());
            Repositorios.Add(typeof(EventosCorreio), new EventosCorreioRepositorio());
            Repositorios.Add(typeof(StatusEntEventoCorreio), new StatusEntEventoCorreioRepositorio());
            Repositorios.Add(typeof(ExpedicaoHistorico), new ExpedicaoHistoricoRepositorio());
            Repositorios.Add(typeof(Vinculo), new VinculoRepositorio());
            Repositorios.Add(typeof(EstoqueIdentificadorExpedicao), new EstoqueIdentificadorExpedicaoRepositorio());
            Repositorios.Add(typeof(ConfiguracaoManager), new ConfiguracaoManagerRepositorio());
            Repositorios.Add(typeof(PlanoContaReferencial), new PlanoContaReferencialRepositorio());
            Repositorios.Add(typeof(FichaTecnicaPCP), new FichaTecnicaPCPRepositorio());
            Repositorios.Add(typeof(FichaTecnicaPCPItem), new FichaTecnicaPCPItemRepositorio());
            Repositorios.Add(typeof(FichaTecnicaPCPRegra), new FichaTecnicaPCPRegraRepositorio());
            Repositorios.Add(typeof(CorreiosPrecoPrazo), new CorreiosPrecoPrazoRepositorio());
            Repositorios.Add(typeof(ArquivoRemessa), new ArquivoRemessaRepositorio());
            Repositorios.Add(typeof(MercadoLivreConfiguracao), new MercadoLivreConfiguracaoRepositorio());
            Repositorios.Add(typeof(PCP_Lote), new PCP_LoteRepositorio());
            Repositorios.Add(typeof(LogRetorno), new LogRetornoRepositorio());
            Repositorios.Add(typeof(LogRetornoDetalhe), new LogRetornoDetalheRepositorio());
            Repositorios.Add(typeof(ProdutoMercadoLivre), new ProdutoMercadoLivreRepositorio());
            Repositorios.Add(typeof(SincronismoPendenteMercadoLivre), new SincronismoPendenteMercadoLivreRepositorio());
            Repositorios.Add(typeof(ContratoControle), new ContratoControleRepositorio());
            Repositorios.Add(typeof(ServicoEnvioCorreio), new ServicoEnvioCorreioRepositorio());
            Repositorios.Add(typeof(FormatoPacoteTransporte), new FormatoPacoteTransporteRepositorio());
            Repositorios.Add(typeof(NotaInutilizada), new NotaInutilizadaRepositorio());
            Repositorios.Add(typeof(PLP), new PLPRepositorio());
            Repositorios.Add(typeof(PLPDetalhe), new PLPDetalheRepositorio());
            Repositorios.Add(typeof(FechamentoCaixa), new FechamentoCaixaRepositorio());
            Repositorios.Add(typeof(FechamentoCaixaRateio), new FechamentoCaixaRateioRepositorio());
            Repositorios.Add(typeof(SisECommerceConfiguracao), new SisECommerceConfiguracaoRepositorio());
            Repositorios.Add(typeof(SincronismoPendenteSisECommerce), new SincronismoPendenteSisECommerceRepositorio());
            Repositorios.Add(typeof(SHLConfiguracao), new SHLConfiguracaoRepositorio());
            Repositorios.Add(typeof(PedidoItemTroca), new PedidoItemTrocaRepositorio());
            Repositorios.Add(typeof(ProdutoFCI), new ProdutoFCIRepositorio());
            Repositorios.Add(typeof(SincronismoPendenteSHL), new SincronismoPendenteSHLRepositorio());
            Repositorios.Add(typeof(PessoaContabilista), new PessoaContabilistaRepositorio());
            Repositorios.Add(typeof(PeriodoApuracaoContabil), new PeriodoApuracaoContabilRepositorio());
            Repositorios.Add(typeof(ConversaoUnidade), new ConversaoUnidadeRepositorio());
            Repositorios.Add(typeof(ProdutoConversao), new ProdutoConversaoRepositorio());
            Repositorios.Add(typeof(FilaDav), new FilaDavRepositorio());
            Repositorios.Add(typeof(PessoaTipoServicoTransporte), new PessoaTipoServicoTransporteRepositorio());
            Repositorios.Add(typeof(Ofd_MedicaoAcompanhamento), new Ofd_MedicaoRepositorioAcompanhamento());
            Repositorios.Add(typeof(Ofd_Ocorrencias), new Ofd_OcorrenciasRepositorio());
            Repositorios.Add(typeof(Ofd_PropostaMedicaoOcorrencias), new Ofd_PropostaMedicaoOcorrenciasRepositorio());
            Repositorios.Add(typeof(Ofd_PropostaRevisaoPerfuracoes), new Ofd_PropostaRevisaoPerfuracoesRepositorio());
            Repositorios.Add(typeof(Ofd_PropostaOrcamentoServicos), new Ofd_PropostaOrcamentoServicosRepositorio());
            Repositorios.Add(typeof(Ofd_AgendamentoMaquina), new Ofd_AgendamentoMaquinaRepositorio());
            Repositorios.Add(typeof(ContratoProduto), new ContratoProdutoRepositorio());
            Repositorios.Add(typeof(Atendimento), new AtendimentoRepositorio());
            Repositorios.Add(typeof(ParametrosContratoProduto), new ParametrosContratoProdutoRepositorio());
            Repositorios.Add(typeof(StatusAtendimento), new StatusAtendimentoRepositorio());
            Repositorios.Add(typeof(FaturamentoAtendimento), new FaturamentoAtendimentoRepositorio());
            Repositorios.Add(typeof(Imposto), new ImpostoRepositorio());
            Repositorios.Add(typeof(CodigoImposto), new CodigoImpostoRepositorio());
            Repositorios.Add(typeof(PedidoItemServico), new PedidoItemServicoRepositorio());
            Repositorios.Add(typeof(LogAlteracaoPedidoItemRepositorio), new LogAlteracaoPedidoItemRepositorio());
            Repositorios.Add(typeof(LogAlteracaoPedidoItem), new LogAlteracaoPedidoItemRepositorio());
            Repositorios.Add(typeof(NotaItemServicoPedidoItemServico), new NotaItemServicoPedidoItemServicoRepositorio());
            Repositorios.Add(typeof(cepbr_estado), new cepbr_estadoRepositorio());
            Repositorios.Add(typeof(cepbr_cidade), new cepbr_cidadeRepositorio());
            Repositorios.Add(typeof(cepbr_bairro), new cepbr_bairroRepositorio());
            Repositorios.Add(typeof(cepbr_endereco), new cepbr_enderecoRepositorio());
            Repositorios.Add(typeof(DadosSubstituto), new DadosSubstitutoRepositorio());
            Repositorios.Add(typeof(LogAlteracaoParticipante), new LogAlteracaoParticipanteRepositorio());
            Repositorios.Add(typeof(VersaoEfdIcmsIpi), new VersaoEfdIcmsIpiRepositorio());
            Repositorios.Add(typeof(Entrega), new EntregaRepositorio());
            Repositorios.Add(typeof(Ofd_AgendamentoMaquinaOcorrencia), new Ofd_AgendamentoMaquinaOcorrenciaRepositorio());
            Repositorios.Add(typeof(EntregaItem), new EntregaItemRepositorio());
            Repositorios.Add(typeof(StatusContato), new StatusContatoRepositorio());
            Repositorios.Add(typeof(Contato), new ContatoRepositorio());
            Repositorios.Add(typeof(ContatoDetalhe), new ContatoDetalheRepositorio());
            Repositorios.Add(typeof(ProdutoServico), new ProdutoServicoRepositorio());
            Repositorios.Add(typeof(Rota), new RotaRepositorio());
            Repositorios.Add(typeof(RotaDetalhe), new RotaDetalheRepositorio());
            Repositorios.Add(typeof(Imei), new ImeiRepositorio());
            Repositorios.Add(typeof(Custo), new CustoRepositorio());
            Repositorios.Add(typeof(StatusOS), new StatusOSRepositorio());
            Repositorios.Add(typeof(CotacaoTransportadoraPedido), new CotacaoTransportadoraPedidoRepositorio());
            Repositorios.Add(typeof(FluxoCaixa), new FluxoCaixaRepositorio());
            Repositorios.Add(typeof(SangriaCaixa), new SangriaCaixaRepositorio());
            Repositorios.Add(typeof(SuprimentoCaixa), new SuprimentoCaixaRepositorio());
            Repositorios.Add(typeof(ProdutoVarejo), new ProdutoVarejoRepositorio());
            Repositorios.Add(typeof(MovimentacaoCreditoPedido), new MovimentacaoCreditoPedidoRepositorio());
            Repositorios.Add(typeof(Moeda), new MoedaRepositorio());
            Repositorios.Add(typeof(CotacaoMoeda), new CotacaoMoedaRepositorio());
            Repositorios.Add(typeof(CondicaoFornecimento), new CondicaoFornecimentoRepositorio());
            Repositorios.Add(typeof(FollowUp), new FollowUpRepositorio());
            Repositorios.Add(typeof(PedidoAnexo), new PedidoAnexoRepositorio());
            Repositorios.Add(typeof(ProdutoAnexo), new ProdutoAnexoRepositorio());
            Repositorios.Add(typeof(Fabricante), new FabricanteRepositorio());
            Repositorios.Add(typeof(Maquina), new MaquinaRepositorio());
            Repositorios.Add(typeof(PedidoMaquina), new PedidoMaquinaRepositorio());
            Repositorios.Add(typeof(OrdemServicoMaquina), new OrdemServicoMaquinaRepositorio());
            Repositorios.Add(typeof(Responsavel), new ResponsavelRepositorio());
            Repositorios.Add(typeof(PessoaResponsavelServico), new PessoaResponsavelServicoRepositorio());
            Repositorios.Add(typeof(ServicoResponsavel), new ServicoResponsavelRepositorio());
            Repositorios.Add(typeof(LogExportacaoNota), new LogExportacaoNotaRepositorio());

            Repositorios.Add(typeof(CteCarga), new CteCargaRepositorio());
            Repositorios.Add(typeof(CteCargaInfo), new CteCargaInfoRepositorio());
            Repositorios.Add(typeof(CteDocumentosInformados), new CteDocumentosInformadosRepositorio());
            Repositorios.Add(typeof(CteIdentificacao), new CteIdentificacaoRepositorio());
            Repositorios.Add(typeof(CtePrestacao), new CtePrestacaoRepositorio());
            Repositorios.Add(typeof(CtePrestacaoComplemento), new CtePrestacaoComplementoRepositorio());
            Repositorios.Add(typeof(CteSeguradora), new CteSeguradoraRepositorio());

            Repositorios.Add(typeof(ProdutoEcommerceSimplificado), new ProdutoEcommerceSimplificadoRepositorio());

            Repositorios.Add(typeof(AverbacaoSeguradoraMdfe), new AverbacaoSeguradoraMdfeRepositorio());
            Repositorios.Add(typeof(CarregamentoMdfe), new CarregamentoMdfeRepositorio());
            Repositorios.Add(typeof(Condutor), new CondutorRepositorio());
            Repositorios.Add(typeof(ContratanteMdfe), new ContratanteMdfeRepositorio());
            Repositorios.Add(typeof(EventoMdfe), new EventoMdfeRepositorio());
            Repositorios.Add(typeof(LacreRodoviarioMdfe), new LacreRodoviarioMdfeRepositorio());
            Repositorios.Add(typeof(Mdfe), new MdfeRepositorio());
            Repositorios.Add(typeof(MovimentoFiscalMdfe), new MovimentoFiscalMdfeRepositorio());
            Repositorios.Add(typeof(NfeReferenciadaMdfe), new NfeReferenciadaMdfeRepositorio());
            Repositorios.Add(typeof(PercursoMdfe), new PercursoMdfeRepositorio());
            Repositorios.Add(typeof(ProprietarioVeiculoMdfe), new ProprietarioVeiculoMdfeRepositorio());
            Repositorios.Add(typeof(ResponsavelSeguroCargaMdfe), new ResponsavelSeguroCargaMdfeRepositorio());
            Repositorios.Add(typeof(Seguradora), new SeguradoraRepositorio());
            Repositorios.Add(typeof(SeguradoraMdfe), new SeguradoraMdfeRepositorio());
            Repositorios.Add(typeof(Veiculo), new VeiculoRepositorio());
            Repositorios.Add(typeof(VeiculoTracaoMdfe), new VeiculoTracaoMdfeRepositorio());

            Repositorios.Add(typeof(Promocao), new PromocaoRepositorio());
            Repositorios.Add(typeof(PromocaoProduto), new PromocaoProdutoRepositorio());
            Repositorios.Add(typeof(OpcaoTributacao), new OpcaoTributacaoRepositorio());

            Repositorios.Add(typeof(ClassificacaoFiscal), new ClassificacaoFiscalRepositorio());
            Repositorios.Add(typeof(ImpostosTributos), new ImpostosTributosRepositorio());
            Repositorios.Add(typeof(PerfilPisCofins), new PerfilPisCofinsRepositorio());
            Repositorios.Add(typeof(PerfilTributarioCliente), new PerfilTributarioClienteRepositorio());

            //Repositorios.Add(typeof(TabelaImpostosTributosExcessoes), new TabelaImpostosTributosExcessoesRepositorio());

            Repositorios.Add(typeof(ImpostosTributosExcessoes), new ImpostosTributosExcessoesRepositorio());

            Repositorios.Add(typeof(PisCofinsNaturezaOperacao), new PisCofinsNaturezaOperacaoRepositorio());

            Repositorios.Add(typeof(TabelaPIS), new TabelaPISRepositorio());
            Repositorios.Add(typeof(TabelaCOFINS), new TabelaCOFINSRepositorio());
            Repositorios.Add(typeof(NaturezaOperacao), new NaturezaOperacaoRepositorio());

            //#Marcador cwkCRUDGenerator
        }

        internal static void Start()
        {
            var i = SessionProvider.SessionFactory;
        }
    }
}