// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Modelo.UserAtributos;

namespace Modelo
{

    public class User
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("registration_date")]
        public string RegistrationDate { get; set; }

        [JsonProperty("first_name")]
        public string FirstName { get; set; }

        [JsonProperty("last_name")]
        public string LastName { get; set; }

        [JsonProperty("country_id")]
        public string CountryId { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("identification")]
        public Identification Identification { get; set; }

        [JsonProperty("address")]
        public Address Address { get; set; }

        [JsonProperty("phone")]
        public Phone Phone { get; set; }

        [JsonProperty("alternative_phone")]
        public AlternativePhone AlternativePhone { get; set; }

        [JsonProperty("user_type")]
        public string UserType { get; set; }

        [JsonProperty("tags")]
        public string[] Tags { get; set; }

        [JsonProperty("logo")]
        public object Logo { get; set; }

        [JsonProperty("points")]
        public int Points { get; set; }

        [JsonProperty("site_id")]
        public string SiteId { get; set; }

        [JsonProperty("permalink")]
        public string Permalink { get; set; }

        [JsonProperty("shipping_modes")]
        public string[] ShippingModes { get; set; }

        [JsonProperty("seller_experience")]
        public string SellerExperience { get; set; }

        [JsonProperty("seller_reputation")]
        public SellerReputation SellerReputation { get; set; }

        [JsonProperty("buyer_reputation")]
        public BuyerReputation BuyerReputation { get; set; }

        [JsonProperty("status")]
        public Status Status { get; set; }

        [JsonProperty("secure_email")]
        public string SecureEmail { get; set; }

        [JsonProperty("credit")]
        public Credit Credit { get; set; }
    }

}
