// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Modelo.VendaAtributos;

namespace Modelo
{

    public class Venda
    {

        [JsonProperty("query")]
        public string Query { get; set; }

        [JsonProperty("display")]
        public string Display { get; set; }

        [JsonProperty("paging")]
        public Paging Paging { get; set; }

        [JsonProperty("results")]
        public Result[] Results { get; set; }

        [JsonProperty("sort")]
        public Sort Sort { get; set; }

        [JsonProperty("available_sorts")]
        public AvailableSort[] AvailableSorts { get; set; }

        [JsonProperty("filters")]
        public object[] Filters { get; set; }

        [JsonProperty("available_filters")]
        public AvailableFilter[] AvailableFilters { get; set; }

        [JsonProperty("complete")]
        public string Complete { get; set; }
    }

}
