// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Modelo.VendaAtributos;

namespace Modelo.VendaAtributos
{

    public class Shipping
    {

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("id")]
        public long? Id { get; set; }

        [JsonProperty("shipment_type")]
        public string ShipmentType { get; set; }

        [JsonProperty("shipping_mode")]
        public object ShippingMode { get; set; }

        [JsonProperty("date_created")]
        public string DateCreated { get; set; }

        [JsonProperty("currency_id")]
        public string CurrencyId { get; set; }

        [JsonProperty("cost")]
        public double? Cost { get; set; }

        [JsonProperty("date_first_printed")]
        public object DateFirstPrinted { get; set; }

        [JsonProperty("service_id")]
        public object ServiceId { get; set; }

        [JsonProperty("receiver_address")]
        public ReceiverAddress ReceiverAddress { get; set; }
    }

}
