// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Modelo.VendaAtributos;

namespace Modelo.VendaAtributos
{

    public class StatusDetail
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("description")]
        public object Description { get; set; }
    }

}
