// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Modelo.UserAtributos;

namespace Modelo.UserAtributos
{

    public class Billing
    {

        [JsonProperty("allow")]
        public bool Allow { get; set; }

        [JsonProperty("codes")]
        public object[] Codes { get; set; }
    }

}
