// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Modelo.UserAtributos;

namespace Modelo.UserAtributos
{

    public class Transactions
    {

        [JsonProperty("period")]
        public string Period { get; set; }

        [JsonProperty("total")]
        public int Total { get; set; }

        [JsonProperty("completed")]
        public int Completed { get; set; }

        [JsonProperty("canceled")]
        public int Canceled { get; set; }

        [JsonProperty("ratings")]
        public Ratings Ratings { get; set; }
    }

}
